<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Managment.aspx.cs" Inherits="Podchody.Page.Managment" MasterPageFile="~/Page/Stalking.Master" %>

<asp:Content ID="Main" ContentPlaceHolderID="MainContent" runat="server">
    <asp:Button ID="NewGameButton" Text="Nowa gra" runat="server" OnClick="NewGameButton_Click" />
    <h3>Drużyny</h3>
    <asp:GridView ID="TeamGridView" runat="server" AutoGenerateColumns="true" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateSelectButton="True" OnSelectedIndexChanged="TeamDataGrid_SelectedIndexChanged"/>
    <h3>Stacje</h3>
    <asp:DropDownList ID="StationDropDownList" runat="server" OnSelectedIndexChanged="StationDropDownList_SelectedIndexChanged" AutoPostBack="true">
    </asp:DropDownList>
    <asp:GridView ID ="StationGridView" runat="server" AutoGenerateColumns="true">
    </asp:GridView>
    <h3>Zadania specjalne</h3>
    <asp:DropDownList ID="SpecialTaskDropDownList" runat="server" OnSelectedIndexChanged="SpecialTaskDropDownList_SelectedIndexChanged" AutoPostBack="true">
    </asp:DropDownList>
    <asp:GridView ID ="SpecialTaskGridView" runat="server">
    </asp:GridView>
    <h3>Podpowiedzi</h3>
    <asp:DropDownList ID="HintDropDownList" runat="server" OnSelectedIndexChanged="SpecialTaskDropDownList_SelectedIndexChanged" AutoPostBack="true">
    </asp:DropDownList>
    <asp:GridView ID ="HintGridView" runat="server">
    </asp:GridView>

</asp:Content>
